"""Auto-generated by scripts/generate_models.py. Do not edit.

Regenerate with:
    uv run python packages/otter_ai_assistant_provider_stream/scripts/generate_models.py

Source: hand-curated (models.dev carries no first-party realtime models for
openai/zai). See ``_REALTIME_MODELS`` in the generator.
"""

from __future__ import annotations

from typing import Any

# A flat list of RealtimeModel-shaped dicts, validated into models at
# catalog load time (see realtime_catalog.load_generated_realtime_catalog).
REALTIME_CATALOG: list[dict[str, Any]] = [
{
        'id': 'gpt-4o-mini-realtime-preview',
        'name': 'GPT-4o mini Realtime Preview',
        'provider': 'openai',
        'base_url': 'https://api.openai.com/v1',
        'api': 'realtime',
        'input_modalities': [
'text'
        ],
        'context_window': 128000,
        'max_tokens': 4096,
        'cost': {
            'input': 0.6,
            'output': 2.4,
            'cache_read': 0.3,
            'cache_write': 0.0
        }
    },
{
        'id': 'gpt-4o-mini-realtime-preview-2024-12-17',
        'name': 'GPT-4o mini Realtime Preview (2024-12-17)',
        'provider': 'openai',
        'base_url': 'https://api.openai.com/v1',
        'api': 'realtime',
        'input_modalities': [
'text'
        ],
        'context_window': 128000,
        'max_tokens': 4096,
        'cost': {
            'input': 0.6,
            'output': 2.4,
            'cache_read': 0.3,
            'cache_write': 0.0
        }
    },
{
        'id': 'gpt-4o-realtime-preview',
        'name': 'GPT-4o Realtime Preview',
        'provider': 'openai',
        'base_url': 'https://api.openai.com/v1',
        'api': 'realtime',
        'input_modalities': [
'text'
        ],
        'context_window': 128000,
        'max_tokens': 4096,
        'cost': {
            'input': 5.0,
            'output': 20.0,
            'cache_read': 2.5,
            'cache_write': 0.0
        }
    },
{
        'id': 'gpt-4o-realtime-preview-2024-12-17',
        'name': 'GPT-4o Realtime Preview (2024-12-17)',
        'provider': 'openai',
        'base_url': 'https://api.openai.com/v1',
        'api': 'realtime',
        'input_modalities': [
'text'
        ],
        'context_window': 128000,
        'max_tokens': 4096,
        'cost': {
            'input': 5.0,
            'output': 20.0,
            'cache_read': 2.5,
            'cache_write': 0.0
        }
    }
]

__all__ = ["REALTIME_CATALOG"]
