from __future__ import annotations

from otter_ai_core.builder import BuilderFn
from otter_ai_core.context import (
    AssistantContent,
    AssistantContextItem,
    AssistantMessage,
    AssistantMessageDiagnostic,
    Context,
    ContextItem,
    DiagnosticErrorInfo,
    ImageContent,
    Message,
    StopReason,
    TextContent,
    ThinkingContent,
    Tool,
    ToolCall,
    ToolResultContextItem,
    ToolResultMessage,
    Usage,
    UsageCost,
    UserContent,
    UserContextItem,
    UserMessage,
    context_item,
)
from otter_ai_core.default_channel import DefaultChannel, create_default_channel
from otter_ai_core.default_model_controller import DefaultModelController, State
from otter_ai_core.interfaces import (
    AbortableConnection,
    AbortableStream,
    AbortObservable,
    AgentTool,
    Channel,
    Connection,
    Emitter,
    EventRunner,
    ModelController,
    Stream,
    Subscribable,
    Writer,
)
from otter_ai_core.provider_api_model_options import (
    KnownApis,
    KnownProviders,
    ProviderModelOption,
    ThinkingLevel,
)
from otter_ai_core.session_manager import (
    COMPACTED,
    ENTRY_APPENDED,
    ITEM_ADDED,
    ITEM_UPDATED,
    TREE_CHANGED,
    ActiveToolsChangeEntry,
    BranchSummaryEntry,
    BranchSummaryInput,
    CompactionEntry,
    CustomEntry,
    CustomMessageEntry,
    LabelEntry,
    MessageEntry,
    MessageUpdateEntry,
    ModelChangeEntry,
    SessionDerivedState,
    SessionEntry,
    SessionEntryBase,
    SessionEntryType,
    SessionError,
    SessionErrorCode,
    SessionInfoEntry,
    SessionMetadata,
    SessionProjection,
    SessionStats,
    SessionStore,
    SessionStoreController,
    SessionStoreControllerEventTypes,
    ThinkingLevelChangeEntry,
    TreeChangedPayload,
    apply_compaction_transform,
    apply_updates,
    derive_state,
    entries_to_items,
    project,
)

__version__ = "0.1.0"

__all__ = [
    # version
    "__version__",
    # builder
    "BuilderFn",
    # usage
    "Usage",
    "UsageCost",
    # diagnostics
    "AssistantMessageDiagnostic",
    "DiagnosticErrorInfo",
    # content
    "AssistantContent",
    "ImageContent",
    "TextContent",
    "ThinkingContent",
    "ToolCall",
    "UserContent",
    # tools
    "Tool",
    # messages
    "AssistantMessage",
    "Message",
    "StopReason",
    "ToolResultMessage",
    "UserMessage",
    # context
    "AssistantContextItem",
    "Context",
    "ContextItem",
    "ToolResultContextItem",
    "UserContextItem",
    "context_item",
    # provider/api/model options
    "KnownApis",
    "KnownProviders",
    "ProviderModelOption",
    "ThinkingLevel",
    # interfaces (Protocol contracts: streaming runtime, model-controller role,
    #   and the agent-loop tool-execution seam)
    "AbortObservable",
    "AbortableConnection",
    "AbortableStream",
    "AgentTool",
    "Channel",
    "Connection",
    "Emitter",
    "EventRunner",
    "ModelController",
    "Stream",
    "Subscribable",
    "Writer",
    # default channel (queue-based default implementation of the Channel protocol)
    "DefaultChannel",
    "create_default_channel",
    # model controller (high-level conversation driver over a connection;
    # ``ModelController`` is the Protocol role, ``DefaultModelController`` the impl)
    "DefaultModelController",
    "ModelController",
    "State",
    # session manager (persisted, restorable, observable per-session layer)
    "SessionStoreController",
    "SessionStore",
    "SessionEntryType",
    "SessionEntryBase",
    "MessageEntry",
    "MessageUpdateEntry",
    "ModelChangeEntry",
    "ThinkingLevelChangeEntry",
    "ActiveToolsChangeEntry",
    "CompactionEntry",
    "BranchSummaryEntry",
    "CustomEntry",
    "CustomMessageEntry",
    "LabelEntry",
    "SessionInfoEntry",
    "SessionEntry",
    "SessionDerivedState",
    "SessionProjection",
    "apply_compaction_transform",
    "apply_updates",
    "derive_state",
    "entries_to_items",
    "project",
    "SessionMetadata",
    "BranchSummaryInput",
    "SessionStats",
    "SessionError",
    "SessionErrorCode",
    "SessionStoreControllerEventTypes",
    "TreeChangedPayload",
    "ENTRY_APPENDED",
    "ITEM_ADDED",
    "ITEM_UPDATED",
    "COMPACTED",
    "TREE_CHANGED",
]
